#!/bin/bash
#add new resolution "1368x768_60.0" => generated by using "cvt 1368 768"
xrandr --newmode "1368x768_60.00"   85.25  1368 1440 1576 1784  768 771 781 798 -hsync +vsync

#add newmode to VGA1 port
xrandr --addmode VGA1 1368x768_60.00

#activate the new mode on VGA1 port
xrandr --output VGA1 --mode 1368x768_60.00

exit 0

